version: '3'

volumes:
    om30-postgres-data:
        driver: local

    om30-redis-data:
        driver: local

services:
    postgres:
        image: postgres:alpine
        container_name: om30-postgres
        volumes:
            - om30-postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=123456
            - POSTGRES_DB=om30
            - POSTGRES_USER=om30

    cache:
        image: redis:latest
        container_name: om30-redis
        command: --appendonly yes
        volumes:
            - om30-redis-data:/data
        ports:
            - "6379:6379"

    app:
        image: ambientum/php:8.1-nginx
        container_name: om30-app
        volumes:
            - .:/var/www/app
        ports:
            - "8080:8080"
            - "8083:8083"
        links:
            - postgres
            - cache
